// ============================================================================
// constants/achievements.js — All achievement definitions
// ============================================================================

export const ACHIEVEMENTS = {
  firstQuiz:        { id: 'firstQuiz',        name: '🌟 Beginner',           desc: 'Complete your first quiz',                   icon: '🌟' },
  fiveQuizzes:      { id: 'fiveQuizzes',       name: '📚 Getting Started',    desc: 'Complete 5 quizzes',                         icon: '📚' },
  tenQuizzes:       { id: 'tenQuizzes',        name: '🎓 Dedicated Learner',  desc: 'Complete 10 quizzes',                        icon: '🎓' },
  twentyQuizzes:    { id: 'twentyQuizzes',     name: '🏅 Quiz Veteran',       desc: 'Complete 20 quizzes',                        icon: '🏅' },
  fiftyQuizzes:     { id: 'fiftyQuizzes',      name: '🦁 Exam Warrior',       desc: 'Complete 50 quizzes',                        icon: '🦁' },
  hundredQuizzes:   { id: 'hundredQuizzes',    name: '💯 Century Scholar',    desc: 'Complete 100 quizzes',                       icon: '💯' },
  perfectScore:     { id: 'perfectScore',      name: '🎯 Perfect',            desc: 'Score 100% on a quiz',                       icon: '🎯' },
  threePerfects:    { id: 'threePerfects',     name: '✨ Hat-Trick',          desc: 'Score 100% three times',                     icon: '✨' },
  tenPerfects:      { id: 'tenPerfects',       name: '🏆 Flawless',           desc: 'Score 100% ten times',                       icon: '🏆' },
  ninetyPlus:       { id: 'ninetyPlus',        name: '⭐ Excellence',         desc: 'Score 90%+ on a quiz',                       icon: '⭐' },
  streak3:          { id: 'streak3',           name: '🔥 On a Roll',          desc: '3-day streak',                               icon: '🔥' },
  streak7:          { id: 'streak7',           name: '🔥 On Fire',            desc: '7-day streak',                               icon: '🔥' },
  streak14:         { id: 'streak14',          name: '🔥 Unstoppable',        desc: '14-day streak',                              icon: '🔥' },
  streak30:         { id: 'streak30',          name: '💪 Dedicated',          desc: '30-day streak',                              icon: '💪' },
  streak60:         { id: 'streak60',          name: '👑 Iron Will',          desc: '60-day streak',                              icon: '👑' },
  allSubjects:      { id: 'allSubjects',       name: '📖 Scholar',            desc: 'Attempt all 9 subjects',                     icon: '📖' },
  speedDemon:       { id: 'speedDemon',        name: '⚡ Speed Demon',        desc: 'Finish with 10+ secs left per question',      icon: '⚡' },
  nightOwl:         { id: 'nightOwl',          name: '🦉 Night Owl',          desc: 'Study after 10 PM',                          icon: '🦉' },
  earlyBird:        { id: 'earlyBird',         name: '🌅 Early Bird',         desc: 'Study before 7 AM',                          icon: '🌅' },
  learnMode:        { id: 'learnMode',         name: '📖 Curious Mind',       desc: 'Complete a full learn-mode topic',            icon: '📖' },
  tenTopics:        { id: 'tenTopics',         name: '🧠 Topic Master',       desc: 'Complete 10 learn-mode topics',               icon: '🧠' },
  twentyFiveTopics: { id: 'twentyFiveTopics',  name: '🔬 Deep Diver',         desc: 'Complete 25 learn-mode topics',               icon: '🔬' },
  mathematician:    { id: 'mathematician',     name: '🧮 Mathematician',      desc: 'Score 80%+ in Mathematics',                  icon: '🧮' },
  physicist:        { id: 'physicist',         name: '⚛️ Physicist',          desc: 'Score 80%+ in Physics',                      icon: '⚛️' },
  chemist:          { id: 'chemist',           name: '🧪 Chemist',            desc: 'Score 80%+ in Chemistry',                    icon: '🧪' },
  biologist:        { id: 'biologist',         name: '🔬 Biologist',          desc: 'Score 80%+ in Biology',                      icon: '🔬' },
  economist:        { id: 'economist',         name: '📊 Economist',          desc: 'Score 80%+ in Economics',                    icon: '📊' },
  accountant:       { id: 'accountant',        name: '💰 Accountant',         desc: 'Score 80%+ in Accounting',                   icon: '💰' },
  literatureLover:  { id: 'literatureLover',   name: '📖 Literature Lover',   desc: 'Score 80%+ in Literature',                   icon: '📖' },
  governmentGuru:   { id: 'governmentGuru',    name: '🏛️ Government Guru',    desc: 'Score 80%+ in Government',                   icon: '🏛️' },
  englishExpert:    { id: 'englishExpert',     name: '📝 English Expert',     desc: 'Score 80%+ in English',                      icon: '📝' },
  novelReader:      { id: 'novelReader',       name: '📗 Novel Reader',       desc: 'Score 80%+ in Novel',                        icon: '📗' },
  challengeWinner:  { id: 'challengeWinner',   name: '🏆 Challenge Winner',   desc: 'Win your first challenge',                   icon: '🏆' },
  challengeStreak3: { id: 'challengeStreak3',  name: '⚔️ Combo Fighter',      desc: 'Win 3 challenges in a row',                  icon: '⚔️' },
  shopShopper:      { id: 'shopShopper',       name: '🛍️ Shop Explorer',      desc: 'Visited the Shop',                           icon: '🛍️' },
  premiumMember:    { id: 'premiumMember',     name: '⭐ Premium Member',     desc: 'Subscribed to EliteScholars Premium',         icon: '⭐' },
  dailyLogin:       { id: 'dailyLogin',        name: '📅 Daily Player',       desc: 'Logged in 7 days in a row',                  icon: '📅' },
  gamePlayer:       { id: 'gamePlayer',        name: '🎮 Gamer Scholar',      desc: 'Complete your first game mode round',         icon: '🎮' },
  gamePerfect:      { id: 'gamePerfect',       name: '🕹️ Perfect Run',        desc: 'Complete a game round with 100%',             icon: '🕹️' },
  gameStreak5:      { id: 'gameStreak5',       name: '🎯 Game Streak',        desc: 'Win 5 game rounds in a row',                  icon: '🎯' },
  multiExam:        { id: 'multiExam',         name: '🌍 All-Rounder',        desc: 'Practice 3+ different exam types',            icon: '🌍' },
  levelUp5:         { id: 'levelUp5',          name: '📈 Rising Star',        desc: 'Reach Level 5',                              icon: '📈' },
  levelUp10:        { id: 'levelUp10',         name: '🚀 Level 10',           desc: 'Reach Level 10',                             icon: '🚀' },
  levelUp20:        { id: 'levelUp20',         name: '👑 Level 20',           desc: 'Reach Level 20',                             icon: '👑' },
  xp500:            { id: 'xp500',             name: '💎 500 XP',             desc: 'Earn 500 total XP',                          icon: '💎' },
  xp2000:           { id: 'xp2000',            name: '💎 2,000 XP',           desc: 'Earn 2,000 total XP',                        icon: '💎' },
  xp5000:           { id: 'xp5000',            name: '💎 5,000 XP',           desc: 'Earn 5,000 total XP',                        icon: '💎' },
  comeback:         { id: 'comeback',          name: '💥 Comeback Kid',       desc: 'Score 50%+ after two consecutive fails',      icon: '💥' },
  shareWarrior:     { id: 'shareWarrior',      name: '📣 Share Warrior',      desc: 'Share the app 3 times',                      icon: '📣' },
};